project:
  type: website

website:
  title: "Utopia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - mykes.qmd
      - hexbrau.qmd
      - about.qmd
      
lang: pt

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    
execute:
  freeze: auto
    
bibliography: references.bib

editor: visual

