project:
  type: website

website:
  title: "Utopia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hexerei.qmd
        text: Hex.Brau.
      - href: mykes.qmd
        text: Mykes
      - href: about.qmd
        text: Sobre
      
lang: pt

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto
    
bibliography: references.bib

editor: source

