---
title: "Hex.Brau."
---

## ᛃ - 4S (Saison) 
### 02. Fevereiro (Réveillon do Cervejeiro)

A runa *Jera* remete à "colheita anual". *Saison* é estação em francês e também um estilo de cervejas de fazenda. A sazonalidade está super presente nessas cervejas, pois elas eram feitas entre as colheitas. A **4S** é uma **Saison** feita com 4 cereais (aveia, centeio, cevada e trigo) que gratifica com mel e muito lúpulo as 4 estações do ano e todas suas colheitas! Planejada para ser brassada como primeira cerveja do ano, próxima ao dia 03/02, simbolizando o *réveillon* do cervejeiro. Consumida idealmente após pelo menos 4 estações de maturação da **ᛃ**, para inspirar as novas safras do ano.

## ᚹ - Nostalgie (Altbier) 
### 20. Março (Equinócio de Outono)

A runa *Wunjo* remete à "alegria". Nostalgia, em alemão *Nostalgie*, era um sentimento comum entre muitos imigrantes. *Alt* é antigo em alemão e *Altbier* é um estilo muito antigo de cerveja. A **Nostalgie** é uma **Altbier** bem lupulada e que celebra a tradição e as alegrias do passado! Planejada para ser brassada próxima ao equinócio de outono, período em que a natureza inicia seu ciclo de introspecção. Consumida idealmente no outono seguinte, para relembrar da **ᚹ** e se alegrar.

## ᚱ - Ritter (Dark Mild) 
### 13. Abril (Lua Cheia no Outono)

A runa *Reidho* remete à "cavalgada" e simboliza os fluxos naturais e a eterna busca por harmonia. *Ritter* é cavaleiro em alemão e também o nome de uma célebre marca de chocolates. A **Ritter** é um **Dark Mild** com notas de cacau que acompanha perfeitamente qualquer jornada! Brassada próxima à primeira lua cheia do outono, alcança seu auge na travessia entre inverno e primavera, quando a **ᛖ** é brassada.

## ᚠ - Sabbath (Black Ale) 
### 30. Abril (Noite de Walpurgis)

A runa *Fehu* remete à "riqueza". *Sabá* é o descanso necessário para honrar as conquistas do trabalho feito. A ida ao show do Black Sabbath (Porto Alegre / 2013) foi literalmente um "sabá" que marcou o início de ricas amizades. A **Sabbath** é uma **Black Ale** muito rica em maltes e lúpulos feita entre amigos que amam boas cervejas e Black Sabbath! Planejada para ser brassada com o início do frio no hemisfério sul, próximo à tradicional "noite das bruxas". Consumida idealmente próximo ao solstício de inverno, quando o sol se retira e **ᚷ** é brassada.

## ᚷ - Bernstein (Amber Lager) 
### 21. Junho (Solstício de Inverno)

A runa *Gebo* remete à "presentear", ao "encontro e troca" entre seres. *Bernstein* é âmbar em alemão, um presente muito valorizado pela sua raridade e beleza. A origem do nome dessa pedra é ligada ao verbo *brennen*, que significa queimar em alemão. A **Bernstein** é uma **Amber Lager** em que pedras queimadas são utilizadas para conferir um toque caramelizado e levemente defumado! Planejada para ser brassada próxima ao solstício de inverno. Consumida idealmente próxima ao solstício de verão, quando a **ᛋ** é brassada.

## ᛟ - Possession (Doppelbock) 
### 27. Julho (Nascimento do Theodoro)

A runa *Othala* remete à "herança", ao "núcleo interno" da família ou comunidade. *Possession* é a posse, a propriedade sobre algo. *Doppel* é duplo em alemão e no caso tem relação com o *spiritus*, ou vigor da cerveja. A **Possession** é uma **Doppelbock** vigorosa pensada para ser envelhecida e que dá vontade de possuir e guardar para filhos e netos! Planejada para ser brassada nos dias mais frios do ano, perto da data de nascimento do nosso filho. Consumida idealmente nos dias mais frios dos próximos anos, com **ᛟ** em dose dupla.

## ᛖ - Maragato (Weizenbock) 
### 23. Agosto (Fim da Guerra)

A runa *Ehwaz* remete ao "cavalo". "Maragato" era um cavalo muito forte cujo nome foi dado em homenagem aos revolucionários da oposição federalista. *Bock* é uma palavra alemã associada à força animal e *Weizenbock* é uma cerveja forte de trigo. A **Maragato** é uma **Weizenbock** encorpada e escura cuja receita criada em 2009 marcou a revolução da cerveja artesanal na família! Planejada para ser brassada no final do inverno, próximo à data do tratado de paz em 1895. Consumida idealmente quando o minuano começar a bater novamente no ano seguinte, quando a **ᚠ** é brassada.

## ᛞ - DiaD (Dubbel) 
### 22. Setembro (Equinócio de Primavera)

A runa *Dagaz* remete ao "dia". O "dia D" marcou o início da batalha da Normandia e a libertação da Europa da ocupação Nazista. *Dubbel* é um estilo belga de cervejas trapistas que ficou bastante popular após a WWII. A **DiaD** é uma **Dubbel** duplamente caprichada feita para ser apreciada em dias de libertação! Planejada para ser brassada depois do equinócio de primavera, quando os dias ficam mais longos. Consumida idealmente a partir do equinócio oposto, que marca o início do outono e a brassagem da **ᚱ**.

## ᛁ - Eis (Cream Ale) 
### 01. Novembro (Dia de Todos os Santos)

A runa *Isa* remete ao "gelo" ou *Eis*, em alemão. O frio representa uma pausa, ou a própria morte. Para marcar o início das estações mais frias e escuras no Hemisfério Norte, o *Samhain*, ou ano novo celta era celebrado. Tal data se tornou o dia das bruxas, ou véspera do dia de finados. Essa runa está ligada à primavera, ou à retomada da vida. A **Eis** é uma **Cream Ale** super refrescante que quebra a estagnação e também ajuda a amenizar o calor! Planejada para ser brassada no auge da primavera. Consumida idealmente no auge do verão, quando as produções dão uma trégua.

## ᛋ - GT (Saison) 
### 21. Dezembro (Solstício de Verão)

A runa *Sowilo* remete ao "sol", à luz que nos guia. *GrandTour*, ou "grande giro" em francês, foi o nome dado a uma aventura ciclística feita em 2015. Na ocasião, amigos cervejeiros pedalaram de sol à sol pelo sul da Bélgica, região tradicional das cervejas *Saison*. A **GT** é uma **Saison** feita em comemoração à nossa principal estrela e também aos gi
